name: Delete Merged Branch

on:
  push:
    branches:
      - master

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Delete Merged Branch
      run: |
        git fetch --prune

        # Get merged branches excluding master and release/*
        branches=$(git branch --merged | grep -vE '^\*|master|release')

        # Check if any branches are merged
        if [ -n "$branches" ]; then
          # Loop through branches and delete them
          for branch in $branches; do
            git branch -d "$branch"
          done
        else
          echo "No branches to delete."
        fi

        git remote prune origin